version: '3.8'
services:
    php-apache:
        container_name: file-upload-extension-blacklist-40
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
