version: '3.8'
services:
    python-flask:
        container_name: vsnippet-file-upload-overwrite-13
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:1337
